# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zx33Ja1D4yOCmUyVJ7lbIEEG5KL3E1jZ
"""

!pip install ultralytics roboflow supervision

from roboflow import Roboflow
import os

rf = Roboflow(api_key="2OFRWtLUJqdrNuwZhhPk")
#Загрузка проекта и датасета (версия 10, формат YOLOv8 - совместим с YOLOv10)
project = rf.workspace("leo-ueno").project("people-detection-o4rdr")
dataset = project.version(10).download("yolov8")
# Путь к конфигурации датасета
dataset_path = dataset.location
data_yaml_path = os.path.join(dataset_path, "data.yaml")
with open(data_yaml_path, 'r') as f:
    print("Содержимое data.yaml:")
    print(f.read())
train_images = len(os.listdir(os.path.join(dataset_path, "train", "images")))
val_images = len(os.listdir(os.path.join(dataset_path, "valid", "images")))
test_images = len(os.path.join(dataset_path, "test", "images")) if os.path.exists(os.path.join(dataset_path, "test")) else 0
print(f"\nРазмеры датасета:")
print(f"Train: {train_images} изображений")
print(f"Valid: {val_images} изображений")
print(f"Test: {test_images} изображений")
print("\nКлассы: person")

from ultralytics import YOLO

#Загрузка предобученной модели YOLOv10n
model = YOLO("yolov10n.pt")
#Обучение
results = model.train(
    data=data_yaml_path,
    epochs=50,
    imgsz=640,
    batch=16,
    name="yolov10n_people_detection",
    device=0
)

#Валидация на тестовой выборке
metrics = model.val(data=data_yaml_path)
#Вывод метрик
print("Метрики валидации:")
print(f"mAP@0.5: {metrics.box.map50:.4f}")
print(f"mAP@0.5:0.95: {metrics.box.map:.4f}")
print("\nПолные метрики:")
print(metrics)

import supervision as sv
from PIL import Image
import matplotlib.pyplot as plt

test_image_path = os.path.join(dataset_path, "test", "images")
if os.path.exists(os.path.join(dataset_path, "test", "images")):
    test_images = os.listdir(os.path.join(dataset_path, "test", "images"))
    test_image_path = os.path.join(dataset_path, "test", "images", test_images[0])
else:
    test_images = os.listdir(os.path.join(dataset_path, "valid", "images"))
    test_image_path = os.path.join(dataset_path, "valid", "images", test_images[0])
results = model(test_image_path)

#Визуализация
plt.figure(figsize=(10, 10))
img = Image.open(test_image_path)
plt.imshow(img)
plt.axis('off')

for result in results:
    boxes = result.boxes
    if boxes is not None:
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
            conf = box.conf[0].cpu().numpy()
            cls = int(box.cls[0].cpu().numpy())
            label = f"person {conf:.2f}"
            plt.gca().add_patch(plt.Rectangle((x1, y1), x2-x1, y2-y1, fill=False, color='red', linewidth=2))
            plt.text(x1, y1-10, label, color='red', fontsize=12, bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

plt.title("Визуализация детекций на тестовом изображении")
plt.show()
result.save("detection_result.jpg")
print("Результат сохранен как detection_result.jpg")